/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hernah
 */
public class OrganizationPanel extends javax.swing.JFrame {

    /**
     * Creates new form OrganizationPanel
     */
    
    Connect conn;
    DefaultTableModel tbl;
    public OrganizationPanel() {
        initComponents();
    }
    
    public OrganizationPanel(String username) {
        conn = new Connect();
        initComponents();
        txtUsername.setText(username);
        tbl = (DefaultTableModel) tblOrganization.getModel();
        displayOrganization();
        int accType = conn.checkRestrictionLvl(username);
        if(accType == -1) {
            btnAddEmp.setEnabled(true);
        }
    }
    
    public void displayOrganization() {
        ResultSet rs = conn.displayOrganization(txtUsername.getText());
        try {
            while(rs.next()) {
                boolean status = rs.getBoolean("employeestatus");
                String empstatus;
                if(status) {
                    empstatus = "Active";
                } else {
                    empstatus = "Inactive";
                }
                Object data[] = {rs.getString("employeeUsername"),rs.getString("restrictionlevel"),empstatus};
                tbl.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrganizationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStatus = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnIsActive = new javax.swing.JButton();
        btnIsInactive = new javax.swing.JButton();
        tfEmpUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbRestrict = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnActive = new javax.swing.JRadioButton();
        btnInactive = new javax.swing.JRadioButton();
        btnAddEmp = new javax.swing.JButton();
        btnUpdateEmp = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSubscribe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Organization username:");

        txtUsername.setText("username");

        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee username", "Restriction Level", "Employee status"
            }
        ));
        tblOrganization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrganizationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrganization);

        jLabel3.setText("Status filter");

        btnIsActive.setText("Active");
        btnIsActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsActiveActionPerformed(evt);
            }
        });

        btnIsInactive.setText("Inactive");
        btnIsInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsInactiveActionPerformed(evt);
            }
        });

        tfEmpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmpUsernameActionPerformed(evt);
            }
        });

        jLabel4.setText("Username");

        jLabel6.setText("Employee Credentials");

        jLabel7.setText("Restriction Level");

        cbRestrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No restrictions", "Can Update Only", "Read Only" }));
        cbRestrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRestrictActionPerformed(evt);
            }
        });

        jLabel8.setText("Status");

        btnStatus.add(btnActive);
        btnActive.setText("Active");

        btnStatus.add(btnInactive);
        btnInactive.setText("Inactive");

        btnAddEmp.setText("Add employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        btnUpdateEmp.setText("Update employee");
        btnUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmpActionPerformed(evt);
            }
        });

        btnClear.setText("Clear filters");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton1.setText("Create Inventory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSubscribe.setText("Subscribe");
        btnSubscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubscribeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubscribe))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsername))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUpdateEmp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddEmp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfEmpUsername)
                                            .addComponent(cbRestrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnActive)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnInactive)))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIsActive)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnIsInactive))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnClear)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton1)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername)
                    .addComponent(jButton2)
                    .addComponent(btnSubscribe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnIsActive)
                            .addComponent(btnIsInactive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbRestrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnActive)
                            .addComponent(btnInactive))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddEmp)
                            .addComponent(btnUpdateEmp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRestrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRestrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRestrictActionPerformed

    private void tfEmpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmpUsernameActionPerformed

    private void tblOrganizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrganizationMouseClicked
        // TODO add your handling code here:
        int index=tblOrganization.getSelectedRow();
        String empUsername = (String) tblOrganization.getValueAt(index, 0);
        String restrictionlvl = (String) tblOrganization.getValueAt(index, 1);
        tfEmpUsername.setText(empUsername);
        cbRestrict.setSelectedItem(restrictionlvl);
        if(tblOrganization.getValueAt(index, 2)=="Active") {
            btnActive.setSelected(true);
        } else {
            btnInactive.setSelected(true);
        }
    }//GEN-LAST:event_tblOrganizationMouseClicked

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
        String empUsername = tfEmpUsername.getText();
        String reslvl = (String) cbRestrict.getSelectedItem();
        boolean active = false;
        if(btnActive.isSelected()) {
            active = true;
        } else if(btnInactive.isSelected()) {
            active = false;
        }
        if(empUsername.isEmpty() || empUsername.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter an employee username.");
        } else {
            Employee e = new Employee(txtUsername.getText(),empUsername, reslvl, active);
            int addStatus = conn.addEmployee(e);
            if(addStatus == 0) {
                JOptionPane.showMessageDialog(this, "Employee already exists.");
            }
            tbl.setRowCount(0);
            displayOrganization();
        }
        
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void btnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmpActionPerformed
        // TODO add your handling code here:
        int index=tblOrganization.getSelectedRow();
        String empUsernamePrev = (String) tblOrganization.getValueAt(index, 0);
        String empUsernameNew = tfEmpUsername.getText();
        String reslvl = (String) cbRestrict.getSelectedItem();
        String prevstatus = (String) tblOrganization.getValueAt(index,2);
        boolean changeToInact = false;
        if(prevstatus.equalsIgnoreCase("Active")) {
            changeToInact = true;
        }
        System.out.println(reslvl);
        boolean active = false;
        if(btnActive.isSelected()) {
            active = true;
        } else if(btnInactive.isSelected()) {
            active = false;
        }
        Employee e = new Employee(txtUsername.getText(),empUsernameNew, reslvl, active);
        if(e.isStatus() == false && changeToInact) {
            int input = JOptionPane.showConfirmDialog(null, "This will remove inventory access for this employee. Do you still want to proceed?","Caution",JOptionPane.YES_NO_CANCEL_OPTION);
            if(input==0) conn.updateEmployee(e, empUsernamePrev, txtUsername.getText());
        }
        else {
            conn.updateEmployee(e, empUsernamePrev, txtUsername.getText());
        }
        tbl.setRowCount(0);
        displayOrganization();
    }//GEN-LAST:event_btnUpdateEmpActionPerformed

    private void btnIsActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsActiveActionPerformed
        // TODO add your handling code here:
        tbl.setRowCount(0);
        ResultSet rs = conn.displayOrgFiltered(true);
        try {
            while(rs.next()) {
                boolean status = rs.getBoolean("employeestatus");
                String empstatus;
                if(status) {
                    empstatus = "Active";
                } else {
                    empstatus = "Inactive";
                }
                Object data[] = {rs.getString("employeeUsername"),rs.getString("restrictionlevel"),empstatus};
                tbl.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrganizationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIsActiveActionPerformed

    private void btnIsInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsInactiveActionPerformed
        // TODO add your handling code here:
        tbl.setRowCount(0);
        ResultSet rs = conn.displayOrgFiltered(false);
        try {
            while(rs.next()) {
                boolean status = rs.getBoolean("employeestatus");
                String empstatus;
                if(status) {
                    empstatus = "Active";
                } else {
                    empstatus = "Inactive";
                }
                Object data[] = {rs.getString("employeeUsername"),rs.getString("restrictionlevel"),empstatus};
                tbl.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrganizationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIsInactiveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tbl.setRowCount(0);
        displayOrganization();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateInventory ci = new CreateInventory();
        ci.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSubscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubscribeActionPerformed
        // TODO add your handling code here:
        Subscription s = new Subscription(txtUsername.getText(), conn.subscriptionType(txtUsername.getText()));
        s.show();
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSubscribeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizationPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnActive;
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnClear;
    private javax.swing.JRadioButton btnInactive;
    private javax.swing.JButton btnIsActive;
    private javax.swing.JButton btnIsInactive;
    private javax.swing.ButtonGroup btnStatus;
    private javax.swing.JButton btnSubscribe;
    private javax.swing.JButton btnUpdateEmp;
    private javax.swing.JComboBox<String> cbRestrict;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrganization;
    private javax.swing.JTextField tfEmpUsername;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
