/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Lance Salera
 */
public class Subscription extends javax.swing.JFrame {

    /**
     * Creates new form Subscribe
     */
    String user;
    Connect conn;
    boolean panelClicked = false;
    boolean panel1Clicked = false;
    public Subscription(String username, String subscriptionType) {
        initComponents();
        conn = new Connect();
        user = username;
        String curr = "(Current Subscription)";
        if(subscriptionType.equals("Basic")) {
            rbBasic.setSelected(true);
            rbCorporate.setSelected(false);
            lblBasicSubscription.setText(curr);
            lblCorporateSubscription.setText("");
            btnMakePayment.setVisible(true);
            btnUnsubscribe.setVisible(false);
        } else {
            rbBasic.setSelected(false);
            rbCorporate.setSelected(true);
            lblCorporateSubscription.setText(curr);
            lblBasicSubscription.setText("");
            btnMakePayment.setVisible(false);
            btnUnsubscribe.setVisible(true);
        }
        lblResultMessage.setText("");
    }

    public Subscription() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSubscriptionType = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMonthly = new javax.swing.JPanel();
        lblMonthly = new javax.swing.JLabel();
        pnlAnually = new javax.swing.JPanel();
        lblManually = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rbBasic = new javax.swing.JRadioButton();
        rbCorporate = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnMakePayment = new javax.swing.JButton();
        btnUnsubscribe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPayableCorp = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCorporateSubscription = new javax.swing.JLabel();
        lblBasicSubscription = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblResultMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(5, 6, 6));

        jPanel1.setBackground(new java.awt.Color(5, 6, 6));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment Plan");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Save more on annual plans");

        pnlMonthly.setBackground(new java.awt.Color(51, 51, 51));
        pnlMonthly.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMonthly.setAlignmentX(0.1F);
        pnlMonthly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMonthlyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMonthlyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMonthlyMouseExited(evt);
            }
        });

        lblMonthly.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblMonthly.setForeground(new java.awt.Color(255, 255, 255));
        lblMonthly.setText("Monthly");

        javax.swing.GroupLayout pnlMonthlyLayout = new javax.swing.GroupLayout(pnlMonthly);
        pnlMonthly.setLayout(pnlMonthlyLayout);
        pnlMonthlyLayout.setHorizontalGroup(
            pnlMonthlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonthlyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMonthly)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMonthlyLayout.setVerticalGroup(
            pnlMonthlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonthlyLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblMonthly)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlAnually.setBackground(new java.awt.Color(51, 51, 51));
        pnlAnually.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlAnually.setAlignmentX(0.1F);
        pnlAnually.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAnuallyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAnuallyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAnuallyMouseExited(evt);
            }
        });

        lblManually.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblManually.setForeground(new java.awt.Color(255, 255, 255));
        lblManually.setText("Annually");

        javax.swing.GroupLayout pnlAnuallyLayout = new javax.swing.GroupLayout(pnlAnually);
        pnlAnually.setLayout(pnlAnuallyLayout);
        pnlAnuallyLayout.setHorizontalGroup(
            pnlAnuallyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnuallyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManually)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAnuallyLayout.setVerticalGroup(
            pnlAnuallyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnuallyLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblManually)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(pnlMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAnually, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAnually, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel5.setBackground(new java.awt.Color(5, 6, 6));

        rbBasic.setBackground(new java.awt.Color(5, 6, 6));
        bgSubscriptionType.add(rbBasic);
        rbBasic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbBasic.setForeground(new java.awt.Color(255, 255, 255));
        rbBasic.setText("Basic");
        rbBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBasicActionPerformed(evt);
            }
        });

        rbCorporate.setBackground(new java.awt.Color(5, 6, 6));
        bgSubscriptionType.add(rbCorporate);
        rbCorporate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbCorporate.setForeground(new java.awt.Color(255, 255, 255));
        rbCorporate.setText("Corporate");
        rbCorporate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCorporateActionPerformed(evt);
            }
        });

        btnMakePayment.setBackground(new java.awt.Color(156, 205, 100));
        btnMakePayment.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMakePayment.setForeground(new java.awt.Color(255, 255, 255));
        btnMakePayment.setText("Make Payment");
        btnMakePayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });

        btnUnsubscribe.setBackground(new java.awt.Color(156, 205, 100));
        btnUnsubscribe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUnsubscribe.setForeground(new java.awt.Color(255, 255, 255));
        btnUnsubscribe.setText("Unsubscribe");
        btnUnsubscribe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUnsubscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnsubscribeActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnMakePayment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnUnsubscribe, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnMakePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(btnUnsubscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnMakePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(btnUnsubscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Free");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Best suited for entrepreneurs or small organizations");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("✔");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Create up to five inventories");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("✔");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Maximum of 20 items per inventory");

        lblPayableCorp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPayableCorp.setForeground(new java.awt.Color(255, 255, 255));
        lblPayableCorp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPayableCorp.setText("₱ 999.00");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Month");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Best suited for big organizations or companies");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Unlimited Inventory");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("✔");

        lblCorporateSubscription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCorporateSubscription.setForeground(new java.awt.Color(204, 204, 204));

        lblBasicSubscription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBasicSubscription.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(156, 205, 100));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rbCorporate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCorporateSubscription))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rbBasic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBasicSubscription)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPayableCorp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBasic)
                    .addComponent(jLabel5)
                    .addComponent(lblBasicSubscription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCorporate)
                    .addComponent(lblPayableCorp)
                    .addComponent(lblCorporateSubscription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        lblTitle.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Subscription");

        lblResultMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblResultMessage.setForeground(new java.awt.Color(255, 0, 51));
        lblResultMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        // TODO add your handling code here:
        String subscriptionPlan = null;
        int days;
        lblResultMessage.setText("");
        if(panelClicked) {
            subscriptionPlan = "Monthly";
            days = 30;
        } else if(panel1Clicked) {
            subscriptionPlan = "Annually";
            days = 365;
        } else {
            lblResultMessage.setText("Please select a subscription plan");
            return;
        }
        
        String subscriptionType;
        double payable = 0;
        if(rbBasic.isSelected()) {
            subscriptionType = rbBasic.getText();
        } else if(rbCorporate.isSelected()) {
            subscriptionType = rbCorporate.getText();
            payable = Double.parseDouble(lblPayableCorp.getText().substring(2, lblPayableCorp.getText().indexOf('.')));
        } else {
            lblResultMessage.setText("Please select a subscription type");
            return;
        }
        
        MakePayment m = new MakePayment(user, payable, subscriptionPlan, subscriptionType);
        m.show();
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMakePaymentActionPerformed

    private void rbCorporateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCorporateActionPerformed
        // TODO add your handling code here:
        //        tfPeriod.setEnabled(true);
        //        btnCalc.setEnabled(true);
        //        tfPayment.setEnabled(true);
    }//GEN-LAST:event_rbCorporateActionPerformed

    private void rbBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBasicActionPerformed
        // TODO add your handling code here:
        //        tfPeriod.setEnabled(false);
        //        btnCalc.setEnabled(false);
        //        tfPayment.setEnabled(false);
    }//GEN-LAST:event_rbBasicActionPerformed

    private void pnlMonthlyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMonthlyMouseExited
        // TODO add your handling code here:
        if(!panelClicked) {
            pnlMonthly.setBackground(Color.decode("#333333"));
        }
        pnlMonthly.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlMonthlyMouseExited

    private void pnlMonthlyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMonthlyMouseEntered
        // TODO add your handling code here:
        pnlMonthly.setBackground(Color.decode("#9CCD64"));
        pnlMonthly.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlMonthlyMouseEntered

    private void pnlMonthlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMonthlyMouseClicked
        // TODO add your handling code here:
        panelClicked = true;
        panel1Clicked = false;
        pnlMonthly.setBackground(Color.decode("#9CCD64"));
        pnlAnually.setBackground(Color.decode("#333333"));
        lblPayableCorp.setText("₱ 999.00");
        jLabel13.setText("Month");
    }//GEN-LAST:event_pnlMonthlyMouseClicked

    private void pnlAnuallyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnuallyMouseExited
        // TODO add your handling code here:

        if(!panel1Clicked) {
            pnlAnually.setBackground(Color.decode("#333333"));
        }
        pnlAnually.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlAnuallyMouseExited

    private void pnlAnuallyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnuallyMouseEntered
        // TODO add your handling code here:
        pnlAnually.setBackground(Color.decode("#9CCD64"));
        pnlAnually.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlAnuallyMouseEntered

    private void pnlAnuallyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnuallyMouseClicked
        // TODO add your handling code here:
        panel1Clicked = true;
        panelClicked = false;
        pnlAnually.setBackground(Color.decode("#9CCD64"));
        pnlMonthly.setBackground(Color.decode("#333333"));
        lblPayableCorp.setText("₱ 9000.00");
        jLabel13.setText("Annual");
    }//GEN-LAST:event_pnlAnuallyMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUnsubscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnsubscribeActionPerformed
        // TODO add your handling code here:
//        try {
//            double amount = Double.parseDouble(tfAmount.getText());
//            int p;
//            if(period.equals("Monthly")) {
//                p = Integer.parseInt(lblDays.getText().substring(0, 2));
//            } else {
//                p = Integer.parseInt(lblDays.getText().substring(0, 3));
//            }
//            conn.updateBalance(username, payable);
//            Verification v = new Verification(username, amount, payable, "subscribe", p, lblStype.getText(), 0);
//            conn.subscribe(v);
//            JOptionPane.showMessageDialog(null, "Verifying...");
//            this.dispose();
//        } catch(NumberFormatException n) {
//            lblMessage.setText("Please input a valid amount");
//        } catch (IllegalArgumentException i) {
//            JOptionPane.showMessageDialog(null, i.getMessage());
//        }
    }//GEN-LAST:event_btnUnsubscribeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSubscriptionType;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JButton btnUnsubscribe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBasicSubscription;
    private javax.swing.JLabel lblCorporateSubscription;
    private javax.swing.JLabel lblManually;
    private javax.swing.JLabel lblMonthly;
    private javax.swing.JLabel lblPayableCorp;
    private javax.swing.JLabel lblResultMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAnually;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMonthly;
    private javax.swing.JRadioButton rbBasic;
    private javax.swing.JRadioButton rbCorporate;
    // End of variables declaration//GEN-END:variables
}
