/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hernah
 */
public class VerificationPanel extends javax.swing.JFrame {

    /**
     * Creates new form VerificationPanel
     */
    Connect conn;
    DefaultTableModel tbl;
    public VerificationPanel() {
        initComponents();
        conn = new Connect();
        tbl = (DefaultTableModel) tblVerification.getModel();
        displayTable();
    }
    
    public void displayTable() {
        ResultSet rs = conn.displayVerification();
        try {
            while(rs.next()) {
                String status;
                if(rs.getInt("status")==0) {
                    status = "Pending";
                } else if(rs.getInt("status")==1) {
                    status="Approved";
                } else {
                    status="Rejected";
                }
                
                Object[] data = {rs.getInt("transactionID"), rs.getString("username"),rs.getDouble("amount"),rs.getDouble("balance"),rs.getString("subscriptionType"),rs.getString("transactionType"),status};
                tbl.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerificationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerification = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPending = new javax.swing.JButton();
        btnApproved = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtSubscription = new javax.swing.JTextField();
        txtTransaction = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();
        btnRejected = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPayable = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(862, 441));

        tblVerification.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Username", "Payment", "Payable", "Subscription", "Transaction", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVerification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVerificationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVerification);

        jLabel1.setText("Filter Status");

        btnPending.setText("Pending");
        btnPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingActionPerformed(evt);
            }
        });

        btnApproved.setText("Approved");
        btnApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Username");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Payment");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Subscription ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Transaction");

        txtAmount.setEditable(false);
        txtAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtAmount.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtAmount.setEnabled(false);
        txtAmount.setOpaque(true);
        txtAmount.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtUsername.setEditable(false);
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtUsername.setEnabled(false);
        txtUsername.setOpaque(true);
        txtUsername.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtSubscription.setEditable(false);
        txtSubscription.setForeground(new java.awt.Color(255, 255, 255));
        txtSubscription.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtSubscription.setEnabled(false);
        txtSubscription.setOpaque(true);
        txtSubscription.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtTransaction.setEditable(false);
        txtTransaction.setForeground(new java.awt.Color(255, 255, 255));
        txtTransaction.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTransaction.setEnabled(false);
        txtTransaction.setOpaque(true);
        txtTransaction.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnApprove.setText("Approve");
        btnApprove.setEnabled(false);
        btnApprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApproveMouseClicked(evt);
            }
        });

        btnRejected.setText("Rejected");
        btnRejected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectedActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.setEnabled(false);
        btnReject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRejectMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Payable");

        txtPayable.setEditable(false);
        txtPayable.setForeground(new java.awt.Color(255, 255, 255));
        txtPayable.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtPayable.setEnabled(false);
        txtPayable.setOpaque(true);
        txtPayable.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnClear.setText("Clear Filters");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton1.setText("Back to Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(btnPending)
                        .addGap(12, 12, 12)
                        .addComponent(btnApproved)
                        .addGap(12, 12, 12)
                        .addComponent(btnRejected)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnApprove)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnReject))))
                            .addComponent(btnClear))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPending)
                            .addComponent(btnApproved)
                            .addComponent(btnRejected))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtPayable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApprove)
                            .addComponent(btnReject))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVerificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVerificationMouseClicked
        // TODO add your handling code here:
        int index=tblVerification.getSelectedRow();
        String username = (String) tblVerification.getValueAt(index,1);
        Double payment = (Double) tblVerification.getValueAt(index, 2);
        Double payable = (Double) tblVerification.getValueAt(index, 3);
        String subscription = (String) tblVerification.getValueAt(index, 4);
        String transaction = (String) tblVerification.getValueAt(index, 5);
        txtUsername.setText(username);
        txtAmount.setText(Double.toString(payment));
        txtPayable.setText(Double.toString(payable));
        txtSubscription.setText(subscription);
        txtTransaction.setText(transaction);
        if(tblVerification.getValueAt(index,6)=="Pending") {
            btnApprove.setEnabled(true);
            btnReject.setEnabled(true);
        } else {
            btnApprove.setEnabled(false);
            btnReject.setEnabled(false);
        }
    }//GEN-LAST:event_tblVerificationMouseClicked

    private void btnApproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApproveMouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "This action cannot be reverted. \nDo you still want to proceed?","Approve verification", JOptionPane.YES_NO_OPTION);
        if(input == JOptionPane.YES_OPTION) {
        int index=tblVerification.getSelectedRow();
        int transactionID = (Integer) tblVerification.getValueAt(index,0);
        double amount = (Double) tblVerification.getValueAt(index,2);
        conn.approveTransaction(transactionID);
        tbl.setRowCount(0);
        displayTable();
        btnApprove.setEnabled(false);
        btnReject.setEnabled(false);
        }
    }//GEN-LAST:event_btnApproveMouseClicked

    private void btnRejectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectMouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "This action cannot be reverted. \nDo you still want to proceed?","Approve verification", JOptionPane.YES_NO_OPTION);
        if(input == JOptionPane.YES_OPTION) {
        int index=tblVerification.getSelectedRow();
        int transactionID = (Integer) tblVerification.getValueAt(index,0);
        conn.rejectTransaction(transactionID);
        tbl.setRowCount(0);
        displayTable();
        btnApprove.setEnabled(false);
        btnReject.setEnabled(false);
        }
    }//GEN-LAST:event_btnRejectMouseClicked

    private void btnPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingActionPerformed
        // TODO add your handling code here:
        ResultSet rs = conn.displayVerificationFiltered(0);
        tbl.setRowCount(0);
        try {
            while(rs.next()) {
                String status=null;
                if(rs.getInt("status")==0) {
                    status = "Pending";
                }                
                Object[] data = {rs.getInt("transactionID"), rs.getString("username"),rs.getDouble("amount"),rs.getDouble("balance"),rs.getString("subscriptionType"),rs.getString("transactionType"),status};
                tbl.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerificationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPendingActionPerformed

    private void btnApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedActionPerformed
        // TODO add your handling code here:
            ResultSet rs = conn.displayVerificationFiltered(1);
            tbl.setRowCount(0);
            try {
                while(rs.next()) {
                    String status= null;
                    if(rs.getInt("status")==1) {
                        status="Approved";
                    } 

                    Object[] data = {rs.getInt("transactionID"), rs.getString("username"),rs.getDouble("amount"),rs.getDouble("balance"),rs.getString("subscriptionType"),rs.getString("transactionType"),status};
                    tbl.addRow(data);
                }
            } catch (SQLException ex) {
                Logger.getLogger(VerificationPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnApprovedActionPerformed

    private void btnRejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectedActionPerformed
        // TODO add your handling code here:
        ResultSet rs = conn.displayVerificationFiltered(-1);
        tbl.setRowCount(0);
        try {
            while(rs.next()) {
                String status = null;
                if(rs.getInt("status")==-1) {
                    status="Rejected";
                }
                
                Object[] data = {rs.getInt("transactionID"), rs.getString("username"),rs.getDouble("amount"),rs.getDouble("balance"),rs.getString("subscriptionType"),rs.getString("transactionType"),status};
                tbl.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerificationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRejectedActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tbl.setRowCount(0);
        displayTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerificationPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnApproved;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPending;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnRejected;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVerification;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtPayable;
    private javax.swing.JTextField txtSubscription;
    private javax.swing.JTextField txtTransaction;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
